--#####################################################################
--Assignment 3
--#####################################################################

--CREATE TWO TABLES EMP & EMP_SAL AS PER THE BELOW STRUCTURE:

--EMP:
--Field EID               Constraints
--EMPID                   Primary Key
--NAME                    NOT NULL
--ADDR                    No employee from UTTAM NAGAR
--CITY                    DEL, GGN, FBD, NOIDA
--PHNO                    UNIQUE
--EMAIL                   Should be on Gmail / Yahoo Domain
--DOB                     <= '1-Jan-1990'


--EMP_SAL:
--Field EID               Constraints
--EMPID                   Foreign Key
--DEPT                    HR, MIS, OPS , IT ADMIN, TEMP
--DESI                    ASSO, MGR, VP, DIR
--BASIC                   >=20000
--DOJ                     -

--By default DEPT should be TEMP


--Constraints can be added to an existing column only if all values in that column satisfy the constraint.
--Since we are not sure of the above condition, lets drop the column, add the constraint and re-create it with new values
USE DEMO;
ALTER TABLE EMP DROP COLUMN DOB;
SELECT * FROM EMP;

/* CHANGE CITY TO DELHI WHERE IT IS NOT 'DELHI', 'GURGAON', 'FARIDABAD', 'NOIDA' FOR OUR CONSTRAINTS TO WORK*/
UPDATE EMP SET CITY = 'DELHI' 
WHERE NOT CITY IN ('DELHI', 'GURGAON', 'FARIDABAD', 'NOIDA');
SELECT * FROM EMP;

/* CHANGE ADDRESS TO SOMETHING ELSE IF IT IS LIKE '%UTTAM%NAGAR%' FOR OUR CONSTRAINTS TO WORK*/
UPDATE EMP SET ADDR = '#25/8, PRESIDENCY ROAD' 
WHERE ADDR LIKE '%UTTAM%NAGAR%';
SELECT * FROM EMP;

/* ADD A COLUMN 'DOB' AS IT DOES NOT EXIST IN THE EXISTING TABLE */
ALTER TABLE EMP 
ADD DOB DATE;
SELECT * FROM EMP;

/* UPDATE DOB FOR ALL THE EXISTING RECORDS SUCH THAT THEY COMPLY WITH THE CONSTRAINTS*/
UPDATE EMP SET DOB = '19-SEP-1986' WHERE EID = 'E0001';
UPDATE EMP SET DOB = '22-DEC-1978' WHERE EID = 'E0002';
UPDATE EMP SET DOB = '02-JAN-1989' WHERE EID = 'E0003';
UPDATE EMP SET DOB = '08-MAR-1982' WHERE EID = 'E0004';
UPDATE EMP SET DOB = '15-JUL-1984' WHERE EID = 'E0005';
UPDATE EMP SET DOB = '14-NOV-1979' WHERE EID = 'E0006';
UPDATE EMP SET DOB = '19-FEB-1975' WHERE EID = 'E0007';
UPDATE EMP SET DOB = '23-APR-1968' WHERE EID = 'E0008';
UPDATE EMP SET DOB = '30-JAN-1988' WHERE EID = 'E0009';
UPDATE EMP SET DOB = '05-DEC-1982' WHERE EID = 'E0010';
SELECT * FROM EMP;

--#####################################################################################
-- Adding Constraints
--#####################################################################################

/* ADD CONSTRAINT TO 'DOB' COLUMN */
ALTER TABLE EMP
ADD CONSTRAINT CKDOB CHECK (DOB <= '01-JAN-1990');

/* ADD CONSTRAINT TO 'EID' COLUMN */
ALTER TABLE EMP
ALTER COLUMN EID VARCHAR(5) NOT NULL;

/* ADD CONSTRAINT TO 'EMAIL' COLUMN */
ALTER TABLE EMP
ADD CONSTRAINT MAIL CHECK (EMAIL LIKE '%GMAIL%' OR EMAIL LIKE '%YAHOO%');

/* ADD CONSTRAINT TO 'PHONE' COLUMN */
ALTER TABLE EMP
ADD CONSTRAINT UKPH UNIQUE (PHONE);

/* ADD PRIMARY KEY CONSTRAINT TO 'EID' COLUMN TO SET IT AS PRIMARY KEY*/
ALTER TABLE EMP
ADD CONSTRAINT PK PRIMARY KEY (EID);
SELECT * FROM EMP;

/*#########################################################################################################*/

/* ADD CONSTRAINT TO 'EID' COLUMN. IT SHOULD NOT BE NULL AS IT IS THE PRIMARY KEY */
ALTER TABLE EMP_SAL
ALTER COLUMN EID VARCHAR(5) NOT NULL;

/* ADD FOREIGN KEY CONSTRAINT TO 'EID' COLUMN IN EMP_SAL TABLE TO SET IT AS FOREIGN KEY */
ALTER TABLE EMP_SAL
ADD CONSTRAINT FKID FOREIGN KEY (EID) REFERENCES EMP (EID);

/* ADD CONSTRAINT TO 'DESI' COLUMN TO ALLOW ONLY SPECIFIC ENTRIES*/
ALTER TABLE EMP_SAL
ADD CONSTRAINT chk_val CHECK (DESI in ('ASSO','MGR','VP', 'DIR'));

/* ADD CONSTRAINT TO 'SALARY' COLUMN TO ALLOW VALUES GREATER THAN 20000 */
ALTER TABLE EMP_SAL
ADD CONSTRAINT chk_SAL CHECK (SALARY >= 20000);

/* ADD CONSTRAINT TO 'DEPT' COLUMN TO ALLOW ONLY SPECIFIC ENTRIES*/
ALTER TABLE EMP_SAL
ADD CONSTRAINT chk_DEP CHECK (DEPT in ('HR','MIS','OPS', 'IT', 'ADMIN', 'TEMP'));

/* ADD CONSTRAINT TO 'DEPT' COLUMN TO HAVE DEFAULT ENTRY AS 'TEMP'*/
ALTER TABLE EMP_SAL
ADD CONSTRAINT DEP DEFAULT 'TEMP' FOR DEPT;

/* ##################################################################################################################### */

/* TESTING THE CONSTRAINTS */
INSERT INTO EMP
VALUES ('E0011', 'RAHUL DRAVID', '#103, CONNAUGHT PLACE', 'DELHI', '+91 8527419475', 'DRAVID@GMAIL.COM', '15-JAN-1987');

INSERT INTO EMP_SAL (EID, DESI, DOJ, SALARY)
VALUES ('E0008', 'ASSO', '29-OCT-2012', 1500000);

SELECT * FROM EMP;
SELECT * FROM EMP_SAL;

DELETE FROM EMP
WHERE EID = 'E0011';

DELETE FROM EMP_SAL
WHERE EID = 'E0008';

/* TESTING COMPLETED SUCCESSFULLY */