--#####################################################################
--Assignment 4
--#####################################################################

--In the EMP table, display :
--	CITY WISE COUNT OF EMPLOYEES ARRANGED IN DESCENDING ORDFER
--	DETAILS OF THE EMPLOYEES WHO DOES NOT HAVE AN ACCOUNT ON YAHOO DOMAIN

--From the EMP_SAL table, display:
--DESIGNATION WISE TOTAL COST AND NUMBER OF MEMBERS ARRANGED IN DESCENDING ORDER OF THE TOTAL COST

USE DEMO;

SELECT * FROM EMP;
SELECT * FROM EMP_SAL;

/* CITY WISE COUNT OF EMPLOYEES ARRANGED IN DESCENDING ORDER */
SELECT CITY, COUNT(EID) AS 'EMP_COUNT' FROM EMP
GROUP BY CITY
ORDER BY COUNT(EID) DESC;

/* DETAILS OF EMPLOYEES WHO DOES NOT HAVE AN ACCOUNT ON YAHOO DOMAIN */
SELECT * FROM EMP
WHERE EMAIL NOT LIKE '%YAHOO%';

/* DESIGNATION WISE TOTAL COST AND NUMBER OF MEMBERS ARRANGED IN DESCENDING ORDER OF THE TOTAL COST */
SELECT DESI, COUNT(EID) AS 'NO_OF_MEMBERS', SUM(SALARY) AS 'TOTAL_COST'
FROM EMP_SAL
GROUP BY DESI
ORDER BY SUM(SALARY) DESC;
