--#####################################################################
--Assignment 5
--#####################################################################

--IN THE EMP TABLE DISPLAY :
--	1) EID NAME CITY DOJ DEPT DESI SALARY OF THE DELHI EMPLOYEES
--	2) DETAILS OF ALL THE EMPLOYEES WHOSE SALARY DETAILS ARE NOT AVAILABLE.


USE DEMO;

SELECT * FROM EMP;
SELECT * FROM EMP_SAL;

SELECT EMP.EID, EMP.NAME, EMP.CITY, EMP_SAL.DOJ, EMP_SAL.DEPT, EMP_SAL.DESI, EMP_SAL.SALARY
FROM EMP
INNER JOIN EMP_SAL
ON EMP.EID = EMP_SAL.EID
WHERE EMP.CITY = 'DELHI';

SELECT EMP.EID, EMP.NAME, EMP.CITY, EMP_SAL.DOJ, EMP_SAL.DEPT, EMP_SAL.DESI, EMP_SAL.SALARY
FROM EMP
FULL JOIN EMP_SAL
ON EMP.EID = EMP_SAL.EID
WHERE EMP_SAL.SALARY IS NULL;