--#####################################################################
--Assignment 6
--#####################################################################

--1) CREATE A VIEW EMP_SAL_DETAILS TO GET EID NAME DOJ DEPT DESI SALARY AS BASIC. 
--   ALSO CALCULATE HRA (15% OF BASIC), PF (9% OF BASIC), NET(BASIC+HRA+PF), GROSS(NET-PF).

--2) CREATE A VIEW TO DISPLAY EID, NAME, DOJ, DESI, DEPT OF ALL THE MANAGERS JOINED IN 2013 and 2014.


USE DEMO;

SELECT * FROM EMP;
SELECT * FROM EMP_SAL;

--Delete the views created earlier as we cannot re-create an existing view
DROP VIEW EMP_SAL_DETAILS;
DROP VIEW EMP_MGR;

/* 1) CREATE A VIEW TO GET EID, NAME, DOJ, DEPT, DESI, SALARY. */
/*    ALSO CALCULATE HRA, PF, NET AND GROSS SALARY */
CREATE VIEW EMP_SAL_DETAILS
AS
SELECT EMP.EID, NAME, DOJ, DEPT, DESI, SALARY AS 'BASIC', SALARY * .15 AS 'HRA', SALARY * .09 AS 'PF', 
SALARY + (SALARY*.15) + (SALARY*.09) AS NET, SALARY + (SALARY*.15) AS GROSS
FROM EMP
INNER JOIN EMP_SAL
ON EMP.EID = EMP_SAL.EID;

SELECT * FROM EMP_SAL_DETAILS;

/* 2) CREATE A VIEW TO DISPLAY EID, NAME, DOJ, DESI, DEPT OF ALL THE MANAGERS JOINED IN 2013 and 2014.*/
CREATE VIEW EMP_MGR
AS
SELECT EMP.EID, NAME, DOJ, DESI, DEPT
FROM EMP
INNER JOIN EMP_SAL
ON EMP.EID = EMP_SAL.EID
WHERE DOJ BETWEEN '01-JAN-2013' AND '31-DEC-2014'
AND
DESI = 'MGR';

SELECT * FROM EMP_MGR;
