--#####################################################################
--Assignment 6
--#####################################################################

--	1) : DEPARTMENT WISE TEAM SIZE AND AVERAGE SALARY OF ALL EMPLOYEES.
--	2) : COUNT OF MANAGERS IN THE COMPANY.
--	3) : MAXIMUM & MINIMUM SALARY OF AN ASSOCIATE.
--	4) : DEPARTMENT WISE TEAM SIZE AND AVERAGE SALARY OF DELHI EMPLOYEES.
--	5) : GENERATE OFFICIAL EMAIL OF THE EMPLOYEE TAKING 1STCHARATCET OF FIRST NAME , 1STCHARATCER OF LAST NAME , LAST 3 DIGITS OF EID, FOLLED BY ‘RCG.COM’. EMAIL SHOULD BE IN A UPPER CASE.
--	6) : NAME, CITY , PHNO & EMAIL OF THE EMPLOYEES WHOSE AGE >=40.
--	7) : EID, NAME DOJ OF EMPLOYEES WHO HAVE COMPLETED 5 YEARS IN THE COMPANY
--	8) : DETAILS OF THE ASSOCIATES HAVING BIRTHDAY IN THE CURRENT MONTH
--	9) : EID, DEPT , DESI , SALARY OF THE EMPLOYEE WHO IS GETTING THE MAXIMUM SALARY
--	10): EID, NAME OF EMPLOYEE WHO HAS LONGEST NAME

USE DEMO;

-- 1) : DEPARTMENT WISE TEAM SIZE AND AVERAGE SALARY OF ALL EMPLOYEES.
SELECT DEPT, COUNT(EID) AS 'TEAM SIZE', FLOOR(AVG(SALARY)) AS 'TOTAL COST'
FROM EMP_SAL
GROUP BY DEPT
ORDER BY 'TOTAL COST' DESC;

--#############################################################################################################

-- 2) : COUNT OF MANAGERS IN THE COMPANY.
SELECT DESI, COUNT(EID) AS 'MANAGERS'
FROM EMP_SAL
GROUP BY DESI
HAVING DESI = 'MGR';

--#############################################################################################################

-- 3) : MAXIMUM & MINIMUM SALARY OF AN ASSOCIATE.
SELECT DESI, MAX(SALARY) AS 'MAXIMUM SALARY', MIN(SALARY) AS 'MINIMUM SALARY'
FROM EMP_SAL
GROUP BY DESI
HAVING DESI = 'ASSO';

-- 4) : DEPARTMENT WISE TEAM SIZE AND AVERAGE SALARY OF DELHI EMPLOYEES.
DROP VIEW AVG_SAL_DEL;

CREATE VIEW AVG_SAL_DEL
AS
SELECT EMP.EID, DEPT, CITY, SALARY
FROM EMP
INNER JOIN EMP_SAL
ON EMP.EID = EMP_SAL.EID
WHERE CITY = 'DELHI';

SELECT * FROM AVG_SAL_DEL;

SELECT DEPT, COUNT(EID) AS 'TEAM SIZE', FLOOR(AVG(SALARY)) AS 'AVERAGE SALARY'
FROM AVG_SAL_DEL
GROUP BY DEPT
ORDER BY 'AVERAGE SALARY' DESC;

--#############################################################################################################

-- 5) : GENERATE OFFICIAL EMAIL OF THE EMPLOYEE TAKING 
--      1STCHARATCET OF FIRST NAME , 
--      1STCHARATCER OF LAST NAME , 
--      LAST 3 DIGITS OF EID, 
--      FOLLED BY ‘RCG.COM’. 
--      EMAIL SHOULD BE IN A UPPER CASE.

ALTER TABLE EMP DROP COLUMN OFFICIAL_EMAIL;

ALTER TABLE EMP 
ADD OFFICIAL_EMAIL VARCHAR(15);

UPDATE EMP SET OFFICIAL_EMAIL = UPPER(CONCAT(LEFT (NAME, 1), RIGHT (NAME, 1), RIGHT (EID, 3), '@RCG.COM'));
SELECT * FROM EMP;

--#############################################################################################################

-- 6) : NAME, CITY , PHONE & EMAIL OF THE EMPLOYEES WHOSE AGE >=40.

SELECT NAME, CITY, PHONE, EMAIL, OFFICIAL_EMAIL, DATEDIFF(YY, DOB, GETDATE()) AS 'AGE'
FROM EMP
WHERE DATEDIFF(YY, DOB, GETDATE()) >= 40;

--#############################################################################################################

-- 7) : EID, NAME, DOJ OF EMPLOYEES WHO HAVE COMPLETED 5 YEARS IN THE COMPANY
DROP VIEW FIVE_YR;

CREATE VIEW FIVE_YR
AS
SELECT EID, DOJ, DATEDIFF(YY, DOJ, GETDATE()) AS 'DURATION'
FROM EMP_SAL
WHERE DATEDIFF(YY, DOJ, GETDATE()) >= 5;

SELECT * FROM FIVE_YR

SELECT EMP.EID, EMP.NAME, FIVE_YR.DOJ, FIVE_YR.DURATION
FROM FIVE_YR
INNER JOIN EMP
ON EMP.EID = FIVE_YR.EID;

--#############################################################################################################

-- 8) : DETAILS OF THE ASSOCIATES HAVING BIRTHDAY IN THE CURRENT MONTH

DROP VIEW BIRTHDAY;

CREATE VIEW BIRTHDAY
AS
SELECT EMP.EID, NAME, ADDR, CITY, PHONE, EMAIL, DATENAME(MONTH, DOB) AS MONT
FROM EMP
WHERE DATENAME(MONTH, DOB) = DATENAME(MONTH, GETDATE());

SELECT * FROM BIRTHDAY

SELECT EMP_SAL.EID, EMP_SAL.DESI
FROM BIRTHDAY
INNER JOIN EMP_SAL
ON EMP_SAL.EID = BIRTHDAY.EID
WHERE EMP_SAL.DESI = 'ASSO';

--#############################################################################################################

-- 9) : EID, DEPT, DESI, SALARY OF THE EMPLOYEE WHO IS GETTING THE MAXIMUM SALARY
SELECT EID, DEPT, DESI, SALARY FROM EMP_SAL
WHERE SALARY = (SELECT MAX(SALARY) FROM EMP_SAL)

--#############################################################################################################

-- 10): EID, NAME OF EMPLOYEE WHO HAS LONGEST NAME
SELECT EID, NAME
FROM EMP
WHERE LEN(NAME) = (SELECT MAX(LEN(NAME)) FROM EMP)

