USE DEMO;

SELECT * FROM EMP;
SELECT * FROM EMP_SAL;

/* DROP VIEW EMP_SAL_DETAILS; */

/* CREATE A VIEW TO GET EID, NAME, DOJ, DEPT, DESI, SALARY. ALSO CALCULATE HRA, PF, NET AND GROSS SALARY */
CREATE VIEW EMP_SAL_DETAILS
AS
          SELECT EMP.EID, NAME, DOJ, DEPT, DESI, SALARY AS 'BASIC', SALARY * .15 AS 'HRA', SALARY * .09 AS 'PF', 
		  SALARY + (SALARY*.15) + (SALARY*.09) AS NET, SALARY + (SALARY*.15) AS GROSS
          FROM EMP
          INNER JOIN EMP_SAL
          ON EMP.EID = EMP_SAL.EID;

SELECT * FROM EMP_SAL_DETAILS


